#!/bin/bash
# export SHELL=$(`which zsh`)
export SHELL='/usr/bin/zsh'
exec $SHELL -l
# Update all the dotfiles everytime you login the system
# So that your version is never out of sync from server
# chezmoi update
. "$HOME/.cargo/eng"
